### PR TITLE
Restrict low latency inputs

### PR DESCRIPTION
**Pull request by CaitlinOCallaghan**
- Checks to ensure that the LL-DASH command line input is valid
- Relocate previous LL-DASH input validation from packager_main.cc to packager.cc
- Outputs:

image

image

### CODE REVIEW

**Review by ngarg17 — APPROVED** [review]
Looks great

**Review by ngarg17 — APPROVED** [review]
looks great

**Review by joeyparrish — APPROVED** [review]

**Review by stephenlindauer — APPROVED** [review]
LG!

**Comment by kevleyski** [comment]
Thanks Caitlin!

**Pull request merged**
